"""initial schema from models

Revision ID: 51be991c8090
Revises:
Create Date: 2026-08-07 10:55:51.278967

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "51be991c8090"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "places",
        sa.Column("place_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("address", sa.String(length=300), nullable=True),
        sa.Column("lat", sa.Float(), nullable=False),
        sa.Column("lng", sa.Float(), nullable=False),
        sa.Column("place_url", sa.Text(), nullable=True),
        sa.Column("thumbnail_url", sa.Text(), nullable=True),
        sa.Column(
            "source", sa.String(length=20), server_default="KAKAO", nullable=False
        ),
        sa.Column("source_synced_at", sa.TIMESTAMP(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('RESTAURANT', 'CAFE', 'ACTIVITY')", name="chk_places_category"
        ),
        sa.PrimaryKeyConstraint("place_id"),
    )
    op.create_index("idx_places_category", "places", ["category"], unique=False)
    op.create_index("idx_places_name", "places", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("nickname", sa.String(length=50), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_id", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("provider IN ('LOCAL', 'KAKAO')", name="chk_users_provider"),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "itineraries",
        sa.Column("itinerary_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=100), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("region", sa.String(length=50), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("arrival_time", sa.String(length=10), nullable=False),
        sa.Column("departure_time", sa.String(length=10), nullable=False),
        sa.Column("transportation", sa.String(length=20), nullable=True),
        sa.Column("purpose", sa.String(length=20), nullable=True),
        sa.Column("styles", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "arrival_time IN ('MORNING', 'LUNCH', 'EVENING')",
            name="chk_itineraries_arrival_time",
        ),
        sa.CheckConstraint(
            "departure_time IN ('MORNING', 'LUNCH', 'EVENING')",
            name="chk_itineraries_departure_time",
        ),
        sa.CheckConstraint(
            "purpose IN ('FRIEND', 'FAMILY', 'COUPLE', 'PET', 'PARENTS')",
            name="chk_itineraries_purpose",
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'GENERATED', 'SAVED')", name="chk_itineraries_status"
        ),
        sa.CheckConstraint(
            "transportation IN ('CAR', 'PUBLIC_TRANSPORT')",
            name="chk_itineraries_transportation",
        ),
        sa.CheckConstraint("end_date >= start_date", name="chk_itineraries_dates"),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("itinerary_id"),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("token_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("token_id"),
    )
    op.create_table(
        "itinerary_places",
        sa.Column("itinerary_place_id", sa.UUID(), nullable=False),
        sa.Column("itinerary_id", sa.UUID(), nullable=False),
        sa.Column("place_id", sa.String(length=50), nullable=False),
        sa.Column("day", sa.SmallInteger(), nullable=True),
        sa.Column("time_slot", sa.String(length=10), nullable=True),
        sa.Column("order_in_day", sa.SmallInteger(), nullable=True),
        sa.Column("start_time", sa.String(length=5), nullable=True),
        sa.Column("travel_time_to_next_min", sa.Integer(), nullable=True),
        sa.Column(
            "added_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "time_slot IN ('MORNING', 'LUNCH', 'EVENING')",
            name="chk_itinerary_places_time_slot",
        ),
        sa.CheckConstraint("day >= 1", name="chk_itinerary_places_day"),
        sa.ForeignKeyConstraint(
            ["itinerary_id"], ["itineraries.itinerary_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["place_id"], ["places.place_id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("itinerary_place_id"),
        sa.UniqueConstraint(
            "itinerary_id", "place_id", name="uq_itinerary_places_place"
        ),
    )
    op.create_index(
        "idx_itinerary_places_order",
        "itinerary_places",
        ["itinerary_id", "day", "time_slot", "order_in_day"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_itinerary_places_order", table_name="itinerary_places")
    op.drop_table("itinerary_places")
    op.drop_table("refresh_tokens")
    op.drop_table("itineraries")
    op.drop_table("users")
    op.drop_index("idx_places_name", table_name="places")
    op.drop_index("idx_places_category", table_name="places")
    op.drop_table("places")
    # ### end Alembic commands ###
